# deploymentName: deployment-ip-reverse
# replicas: 2
# image:
#   repository: ebenezery/ip-reverser:latest
#   pullPolicy: IfNotPresent
#   tag: "reverserapp-latest"

# service:
#   type: LoadBalancer
#   port: 80
#   targetPort: 8000

# resources:
#   limits:
#     cpu: 500m
#     memory: 512Mi
#   requests:
#     cpu: 250m
#     memory: 256Mi


deploymentName: deployment-ip-reverse
replicaCount: 2
image:
  repository: ebenezery/ip-reverser
  pullPolicy: Always
  tag: "latest"

service:
  name: ip-reverser
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
