name: K8S CLUSTER IP-REVERSER DEPLOYMENT

on:
  push:
    branches: [ main ]
    tags: [ 'l' ]  
  
env:
  REGISTRY: docker.io
  IMAGE_NAME: ebenezery/ip-reverser

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Build and push Docker image
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # - name: Generate image tag
    #   id: tag
    #   run: |
    #     SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
    #     TIMESTAMP=$(date +%Y%m%d-%H%M%S)
    #     echo "image_tag=staging-${SHORT_SHA}-${TIMESTAMP}" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          # ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.image_tag }}
          # ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      
          docker.io/${{ secrets.DOCKER_USERNAME }}/ip-reverser:latest
          docker.io/${{ secrets.DOCKER_USERNAME }}/ip-reverser:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    # # 2. Update Helm values in Git (this triggers ArgoCD)
    # - name: Update Helm values
    #   run: |
    #     # Update the image tag in values.yaml
    #     sed -i "s|tag: .*|tag: \"${{ steps.tag.outputs.image_tag }}\"|g" helm-chart/values.yaml
    #     
    #     # Show what changed
    #     echo "Updated values.yaml with new image tag:"
    #     grep "tag:" helm-chart/values.yaml
    
    - name: Commit and push updated values
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add helm-chart/values.yaml
        git commit -m "ðŸš€ Update staging image to latest"
        git push
