name: Deploy to k8s cluster

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ebenezery/ip-reverser

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Generate image tag
      id: tag
      run: |
        SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
        echo "image_tag=staging-${SHORT_SHA}" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.image_tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Update Helm values
      run: |
        sed -i "s|tag: .*|tag: \"${{ steps.tag.outputs.image_tag }}\"|g" helm-chart/values.yaml
    
   - name: Commit updated values
     run: |
       git config --local user.email "ebenezeraluko3@gmail.com"
       git config --local user.name "eben"
       git add helm-chart/values.yaml
       git commit -m "Update staging image tag to ${{ steps.tag.outputs.image_tag }}" || exit 0
       git push
    
    #- name: Trigger ArgoCD sync (optional)
    #  run: |
    #    echo "ArgoCD will automatically detect and sync the changes"
        # Optional: Trigger immediate sync
        # curl -X POST "${{ secrets.ARGOCD_SERVER }}/api/v1/applications/your-app-staging/sync" \
        #   -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}"
